name: cheaper-eater-backend

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 19.X
              uses: actions/setup-node@v3
              with:
                  node-version: "19.X"
                  cache: "npm"
            - run: eslint . --ext .mjs,.js,.jsx,.ts,.tsx
            - run: npm ci
            #- run: npm test
